apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-calculator
spec:
  selector:
    matchLabels:
      run: my-calculator
  replicas: 1
  template:
    metadata:
      labels:
        run: my-calculator
    spec:
      containers:
      - name: my-calculator
        image: docker.io/blacksparki/calculator:1.0
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m
---
apiVersion: v1
kind: Service
metadata:
  name: my-calculator
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: my-calculator